name: cad_env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pyside6
  - pyvista
  - pyvistaqt
  - build123d
  - ocp
  - vtk
  - numpy
  - scipy
  - shapely
  - ezdxf
  - loguru
  - trimesh
  - matplotlib
  - pillow
  - lib3mf
